export const URL_CONSTANTS = {
  ENCODE_REQUEST: 'ENCODE_REQUEST',
  ENCODE_SUCCESS: 'ENCODE_SUCCESS',
  ENCODE_FAILURE: 'ENCODE_FAILURE',

  DECODE_REQUEST: 'DECODE_REQUEST',
  DECODE_SUCCESS: 'DECODE_SUCCESS',
  DECODE_FAILURE: 'DECODE_FAILURE',
}
